### ISSUE TITLE
Setting accessToken?

### ISSUE THREAD

**Issue by matthiasdv** [drudge/passport-facebook-token#5]
I'm slightly confused on how to use this. If the implementation is somewhat like decribed in the post here: 

https://github.com/jaredhanson/passport-facebook/issues/26#issuecomment-19650514

then am i correct that i should set req.body.accessToken by a POST request? 

so an app.post route for passport-facebook-token with the accesstoken set by the JS SDK

and a get route for the plain passport-facebook wich provides a token by redirecting through facebook?

**Comment by mdibay1367** [comment]
@matthiasdv Here is the advantage of using post instead of get: Imaging your REST API design is going to be client independent (web-client, IOS, Android). Therefore, using session and cookie doesn' t make sense (ex: mobile platforms don't understand session& cookie). If you decide to use Token Based Authentication (like JWT), you want to send the backend generated token to your client in response header of your login reqest. 

The Get redirect for passport-facebook, redirects to a callback function and it is not possible to send the repsonse header for it. In case you need more information I have already posted a question on stackoverflow.com which explains the problem you would end up using get instead of post: 
http://stackoverflow.com/questions/39738238/passport-facebook-strategy-for-authotization
