### ISSUE TITLE
Dynamic Client ID/Secret

### ISSUE THREAD

**Issue by rodrigoreal** [drudge/passport-facebook-token#59]
I need to use a dynamic client id/secret, depending on the request i'll need to use differents credentials.
Because in the post req i have `passport.authenticate('facebook-token')` and the strategy where i put the credentials is inside another script `config/passport.js`.
Do you have any idea how can i do that?
Thanks

**Comment by ghaiklor** [comment]
@rodrigoreal I suppose, you can create new configuration for Passport on each request, depends on your needs. But, it definitely may decrease performance.

**Comment by rodrigoreal** [comment]
@ghaiklor i was wondering if exist another approach, because as you said it may decrease performance.
But thanks anyway.

**Comment by galkahana** [comment]
I'm wondering as to why they are needed altogether. [in other words, you can put whatever you want]
It seems to me that if the facebook token is provided the original client id and secret are not being used. In fact, only needed so that subclassing oauth2 wouldn't fail, which again, i'm not sure subclassing it gives anything. 
Am i wrong?

**Comment by ghaiklor** [comment]
@galkahana we need this information for proofing - https://github.com/drudge/passport-facebook-token/blob/master/src/index.js#L103

**Comment by galkahana** [comment]
Right. Thank you.

**Comment by Ray0427** [comment]
I have the same problem for login two apps with the same member server.
My solution is copy the strategy and modify the strategy name.
So, when login with the app id, and use the right strategy.

**Comment by joelcoronah** [comment]
I have the same problem could someone help?
