### ISSUE TITLE
npm deployment

### ISSUE THREAD

**Issue by rsegecin** [drudge/passport-facebook-token#92]
Hi, I'd like to know why haven't you pushed the current version to npm? do you think that's missing something? would you like some help?

**Comment by ghaiklor** [comment]
@drudge

**Comment by turbo5** [comment]
This seems like an abandoned project sadly

**Comment by ghaiklor** [comment]
Let me check if I have access to this package on npm...

**Comment by drudge** [comment]
hey @ghaiklor, you do! I think you published the last several releases.

I'm not using this module in production any longer, and have extremely limited time right now.

**Comment by ghaiklor** [comment]
@drudge oh, great, seems I forgot about it 😭
Same situation here, actually, last time I used it several years ago, but now I'm just not doing APIs and stuff anymore.

Anyway, let me tidy up in repo a little and I will publish everything we had in history for 4 years to npm.

**Comment by drudge** [comment]
Thanks my friend! 

If anyone else still using the module would like to contribute, let me know!

**Comment by ghaiklor** [comment]
@rsegecin @turbo5 I tidy up a little in our repo here 1e4eb3dc8e65bd57cf4746108330a2d56ebd9df8.

Did a major update, because I have removed Babel (why do we need it in 2020), updated Node.js supported versions, etc... So you should find a recent release on npm right now. Please report if any issues arise.

**Comment by rsegecin** [comment]
Thank you very much Eugene. That's awesome great job =)
